apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: single
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,single]}
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/single: ""
